version: '2.2'
services:

  django:
    build: .
    # Loading the app is defined here to allow for
    # autoreload on changes it is mounted on top of the
    # old copy that docker added when creating the image
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=False
      - GEONODE_LB_HOST_IP=idesca.munisc.gob.cr
      - GEONODE_LB_PORT=80
      - SITEURL=http://idesca.munisc.gob.cr/
      - ALLOWED_HOSTS=['*','localhost','idesca.munisc.gob.cr', ]
      - GEOSERVER_PUBLIC_LOCATION=http://idesca.munisc.gob.cr/geoserver/

  celery:
    build: .
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=False
      - GEONODE_LB_HOST_IP=idesca.munisc.gob.cr
      - GEONODE_LB_PORT=80
      - SITEURL=http://idesca.munisc.gob.cr/
      - ALLOWED_HOSTS=['*','localhost','idesca.munisc.gob.cr', ]
      - GEOSERVER_PUBLIC_LOCATION=http://idesca.munisc.gob.cr/geoserver/

  geoserver:
    environment:
      - GEONODE_LB_HOST_IP=idesca.munisc.gob.cr
      - GEONODE_LB_PORT=80
  #    - NGINX_BASE_URL=
